// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Swe2023Test {
  private WebDriver driver;

  private WebDriver driver2;
  private Map<String, Object> vars;

  JavascriptExecutor js;


  @Before
  public void setUp() {
    driver = new ChromeDriver();
    driver2 = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
    driver2.quit();
  }
  @Test
  public void swe2023() {
    driver.get("https://www.google.com/search?q=selenium&sxsrf=APwXEdctu5B96TFVUrE5BxoXBd0Kl7PCig%3A1684683397552&source=hp&ei=hTpqZJvbH6-n2roP6O-ogAs&iflsig=AOEireoAAAAAZGpIld2ErW-B4NVst92D9dgXlPCYP0pv&oq=sele&gs_lcp=Cgdnd3Mtd2l6EAMYADIHCCMQigUQJzIECCMQJzIHCCMQigUQJzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIICAAQgAQQsQMyCwguEIAEELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoLCAAQgAQQsQMQgwE6BAgAEAM6BwguEIoFEEM6BQgAEIAEOgcIIxDqAhAnOgcIABCABBAKOg0ILhCKBRDHARCvARBDUABY7A5g-BVoBHAAeACAAZABiAGCCJIBAzAuOJgBAKABAbABCg&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1440, 900));
    {
      WebElement element = driver.findElement(By.cssSelector(".jfN4p"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#rso > .MjjYud:nth-child(1) .LC20lb")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("About Selenium")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(5) span")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) span")).click();
    driver.findElement(By.cssSelector(".order-sm-3")).click();
    driver.close();
  }

  @Test
  public void selenium() {
    driver2.get("https://github.com/");
    driver2.manage().window().setSize(new Dimension(1440, 900));
    driver2.findElement(By.cssSelector(".mr-lg-3 path")).click();
    driver2.findElement(By.cssSelector(".HeaderMenu-item:nth-child(2) > .HeaderMenu-link")).click();
    driver2.findElement(By.linkText("Enterprise")).click();
    driver2.findElement(By.cssSelector(".border-bottom:nth-child(1) > .list-style-none .color-fg-default")).click();
    driver2.findElement(By.linkText("CI/CD & Automation")).click();
    driver2.findElement(By.linkText("Explore Docs")).click();
    driver2.findElement(By.cssSelector("#react-aria-58 .f4 > span")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver2.findElement(By.cssSelector("#react-aria-601 .TruncateLines_truncated__Q8prj > span")).click();
    {
      WebElement element = driver2.findElement(By.cssSelector("#react-aria-994 > .PRIVATE_TreeView-item-content-text"));
      Actions builder = new Actions(driver2);
      builder.moveToElement(element).perform();
    }
    driver2.findElement(By.cssSelector(".mb-4:nth-child(1) .Item__LiBox-sc-yeql7o-0:nth-child(4)")).click();
    driver2.findElement(By.cssSelector("#react-aria-1123 .TruncateLines_truncated__Q8prj > span")).click();
    driver2.close();
  }
}
